In [33]:
print('DECISION TREES')
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.model_selection import cross_val_score

df = pd.read_csv('/Users/loan/diamond1_sprint1.csv')

arr = df.to_numpy()

all_data = arr[:, 0: -1] 
all_labels = arr[:, -1]

x=all_data
y=all_labels

x_train,x_test,y_train,y_test=train_test_split(x, y, test_size=0.2)

dtc = DecisionTreeClassifier()

dtc = dtc.fit(x_train,y_train)

dtc.score(x_test, y_test)

scores = cross_val_score(dtc, x, y, cv=5)

print("Cross Validation Accuracies:")
print(scores)

y_pred = dtc.predict(x_test)

print("Test Data Prediction Accuracy:")
print(dtc.score(x_test,y_test))

importance = dtc.feature_importances_

print('Feature Importance:')
print('kills')
print(importance[0])
print('assists')
print(importance[1])
print('gold')
print(importance[2])
print('average level')
print(importance[3])
print('turret damage')
print(importance[4])
print('dragon kills')
print(importance[5])
print('game length')
print(importance[6])

DECISION TREES
Cross Validation Accuracies:
[0.98496835 0.98364979 0.97731469 0.98311791 0.98285413]
Test Data Prediction Accuracy:
0.984704641350211
Feature Importance:
[0.00482037 0.00775807 0.90925822 0.01969339 0.04888651 0.00477956
 0.00480386]


In [34]:
print('LOGISTIC REGRESSION')

from sklearn.linear_model import LogisticRegression

lrc = LogisticRegression().fit(x_train, y_train)

lrc.predict(x_test)

lrc.predict_proba(x_test)

scores = cross_val_score(lrc, x, y, cv=5)

print("Cross Validation Accuracies:")
print(scores)

print('Test Data Prediction Accuracy:')
print(lrc.score(x_test, y_test))

importance = lrc.coef_[0]

print('Feature Importance:')
print('kills')
print(importance[0])
print('assists')
print(importance[1])
print('gold')
print(importance[2])
print('average level')
print(importance[3])
print('turret damage')
print(importance[4])
print('dragon kills')
print(importance[5])
print('game length')
print(importance[6])

LOGISTIC REGRESSION


/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Cross Validation Accuracies:
[0.98312236 0.98444093 0.98153521 0.98496439 0.98311791]
Test Data Prediction Accuracy:
0.9860232067510548
Feature Importance:
[-1.24590808e-01  8.06751695e-02  5.62667532e-04  2.49922054e-01
  2.80267063e-04  2.73581823e-01  2.04781801e-07]


In [35]:
print('GRADIENT BOOSTING')

from sklearn.ensemble import GradientBoostingClassifier

gbc = GradientBoostingClassifier()

gbc.fit(x_train,y_train)

gbc.predict(x_test)

gbc.predict_proba(x_test)

scores = cross_val_score(gbc, x, y, cv=5)

print("Cross Validation Accuracies:")
print(scores)

print('Test Data Prediction Accuracy:')
print(gbc.score(x_test, y_test))

importance = gbc.feature_importances_

print('Feature Importance:')
print('kills')
print(importance[0])
print('assists')
print(importance[1])
print('gold')
print(importance[2])
print('average level')
print(importance[3])
print('turret damage')
print(importance[4])
print('dragon kills')
print(importance[5])
print('game length')
print(importance[6])

GRADIENT BOOSTING
Cross Validation Accuracies:
[0.98734177 0.99129747 0.9862833  0.98654709 0.98601952]
Test Data Prediction Accuracy:
0.9886603375527426
Feature Importance:
kills
0.0008790087489361035
assists
0.0035841773683207368
gold
0.894672758999574
average level
0.04877533930664544
turret damage
0.0503282666017165
dragon kills
0.0007019364893390474
game length
0.0010585124854681422


In [37]:
print("RANDOM FOREST")

from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier()

rfc.fit(x_train,y_train)

rfc.predict(x_test)

rfc.predict_proba(x_test)

scores = cross_val_score(rfc, x, y, cv=5)

print("Cross Validation Accuracies:")
print(scores)

print('Test Data Prediction Accuracy:')
print(rfc.score(x_test, y_test))

importance = rfc.feature_importances_

print('Feature Importance:')
print('kills')
print(importance[0])
print('assists')
print(importance[1])
print('gold')
print(importance[2])
print('average level')
print(importance[3])
print('turret damage')
print(importance[4])
print('dragon kills')
print(importance[5])
print('game length')
print(importance[6])

RANDOM FOREST
Cross Validation Accuracies:
[0.98734177 0.99129747 0.987866   0.98812978 0.98812978]
Test Data Prediction Accuracy:
0.9889240506329114
Feature Importance:
kills
0.15415714943353342
assists
0.09847706407971625
gold
0.23983775299230542
average level
0.24696169233170057
turret damage
0.22936678066455038
dragon kills
0.021934092116492363
game length
0.009265468381701615


In [38]:
print("NEURAL NETWORKS")

from sklearn.neural_network import MLPClassifier

nnc = MLPClassifier()

nnc.fit(x_train,y_train)

nnc.predict(x_test)

nnc.predict_proba(x_test)

scores = cross_val_score(nnc, x, y, cv=5)

print("Cross Validation Accuracies:")
print(scores)

print('Test Data Prediction Accuracy:')
print(nnc.score(x_test, y_test))

importance = rfc.feature_importances_

print('Feature Importance:')
print('kills')
print(importance[0])
print('assists')
print(importance[1])
print('gold')
print(importance[2])
print('average level')
print(importance[3])
print('turret damage')
print(importance[4])
print('dragon kills')
print(importance[5])
print('game length')
print(importance[6])

NEURAL NETWORKS
Cross Validation Accuracies:
[0.9818038  0.97705696 0.97652334 0.97810604 0.96729095]
Test Data Prediction Accuracy:
0.982331223628692
Feature Importance:
kills
0.15415714943353342
assists
0.09847706407971625
gold
0.23983775299230542
average level
0.24696169233170057
turret damage
0.22936678066455038
dragon kills
0.021934092116492363
game length
0.009265468381701615


In [39]:
print("KNN")

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()

knn.fit(x_train,y_train)

knn.predict(x_test)

knn.predict_proba(x_test)

scores = cross_val_score(knn, x, y, cv=5)

print("Cross Validation Accuracies:")
print(scores)

print('Test Data Prediction Accuracy:')
print(knn.score(x_test, y_test))

importance = rfc.feature_importances_

print('Feature Importance:')
print('kills')
print(importance[0])
print('assists')
print(importance[1])
print('gold')
print(importance[2])
print('average level')
print(importance[3])
print('turret damage')
print(importance[4])
print('dragon kills')
print(importance[5])
print('game length')
print(importance[6])

KNN
Cross Validation Accuracies:
[0.97837553 0.9757384  0.97494065 0.97731469 0.97889739]
Test Data Prediction Accuracy:
0.9791666666666666
Feature Importance:
kills
0.15415714943353342
assists
0.09847706407971625
gold
0.23983775299230542
average level
0.24696169233170057
turret damage
0.22936678066455038
dragon kills
0.021934092116492363
game length
0.009265468381701615
